project:
  type: book
  output-dir: docs

book:
  title: "Astral Projection's Progress Journal"
  repo-url: https://github.com/pjournal/mef07g-astralprojection
  chapters:
    - index.qmd
    - assignment1.qmd
    - eda.qmd
  page-footer:
    center: "[MEF BDA 503](https://mef-bda503.github.io)"
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo

    
    


