project:
  type: book
  output-dir: docs

book:
  title: "Astral Projection Progress Journal"
  repo-url: https://pjournal.github/mef07g-astralprojection
  chapters:
    - index.qmd
    - assignment1.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
    
    
    


