---
title: "Preprocessing"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 1
    number_sections: true
editor: visual
---

# Preprocessing

## Initial Setup

```{r}

#install.packages("WDI",repos = "http://cran.us.r-project.org",dependencies=TRUE,eval=FALSE)
library(WDI)


#install.packages("remotes",repos = "http://cran.us.r-project.org",dependencies=TRUE,eval=FALSE)
library(remotes)

#install_github('vincentarelbundock/WDI')

```

## Data Preparation

```{r}
indicator_codes <- c("SP.POP.TOTL","NY.GDP.PCAP.CD","SP.POP.DPND","FP.CPI.TOTL.ZG","SL.UEM.TOTL.ZS","SL.TLF.CACT.FE.ZS","SL.TLF.CACT.MA.ZS")
countries <- c("TUR", "USA")
start_date <- 2018
end_date <- 2023
world_bank_data_2 <- WDI( indicator = indicator_codes,
                        country = countries,
                        start = start_date, 
                        end = end_date, 
                        extra = TRUE)

world_bank_data_summary <- world_bank_data_2[,c("country","year","SP.POP.TOTL","NY.GDP.PCAP.CD","SP.POP.DPND","FP.CPI.TOTL.ZG","SL.UEM.TOTL.ZS","SL.TLF.CACT.FE.ZS","SL.TLF.CACT.MA.ZS")]
colnames(world_bank_data_summary) <- c("Country","Year","Population","GdpPerCapita","AgeDependancyRatio","Inflation","UnemploymentRate","FemaleLaborRate","MaleLaborRate")
world_bank_data_summary
```

## Save as .rds File

```{r}
saveRDS(world_bank_data_summary, file = "world_bank_data.rds")
loaded_data <- readRDS("world_bank_data.rds")
loaded_data

```

## Preprocessed Data Link

## [Data Link](https://github.com/pjournal/mef07g-astralprojection/blob/main/world_bank_data.rds)
